export const PERSONA_REPLY_JSON_SCHEMA = {
  name: "persona_reply",
  strict: true,
  // Definerer hvilke felter modellen må returnere når den skriver et svar inkl. actions
  schema: {
    type: "object",
    additionalProperties: false,
    properties: {
      reply: { type: "string" },
      actions: {
        type: "array",
        items: {
          type: "object",
          additionalProperties: false,
          properties: {
            type: {
              type: "string",
              enum: [
                "update_shipping_address",
                "cancel_order",
                "refund_order",
                "change_shipping_method",
                "hold_or_release_fulfillment",
                "edit_line_items",
                "update_customer_contact",
                "add_note",
                "add_tag",
                "add_internal_note_or_tag",
                "resend_confirmation_or_invoice",
              ],
            },
            orderId: { type: "number" },
            payload: {
              type: "object",
              additionalProperties: false,
              properties: {
                shipping_address: {
                  anyOf: [
                    {
                      type: "object",
                      additionalProperties: false,
                      properties: {
                        name: { anyOf: [{ type: "string" }, { type: "null" }] },
                        address1: { anyOf: [{ type: "string" }, { type: "null" }] },
                        address2: { anyOf: [{ type: "string" }, { type: "null" }] },
                        zip: { anyOf: [{ type: "string" }, { type: "null" }] },
                        city: { anyOf: [{ type: "string" }, { type: "null" }] },
                        country: { anyOf: [{ type: "string" }, { type: "null" }] },
                        phone: { anyOf: [{ type: "string" }, { type: "null" }] },
                      },
                      required: [
                        "name",
                        "address1",
                        "address2",
                        "zip",
                        "city",
                        "country",
                        "phone",
                      ],
                    },
                    { type: "null" },
                  ],
                },
                note: { anyOf: [{ type: "string" }, { type: "null" }] },
                tag: { anyOf: [{ type: "string" }, { type: "null" }] },
                amount: { anyOf: [{ type: "number" }, { type: "null" }] },
                currency: { anyOf: [{ type: "string" }, { type: "null" }] },
                reason: { anyOf: [{ type: "string" }, { type: "null" }] },
                refund: { anyOf: [{ type: "boolean" }, { type: "null" }] },
                restock: { anyOf: [{ type: "boolean" }, { type: "null" }] },
                email: { anyOf: [{ type: "string" }, { type: "null" }] },
                phone: { anyOf: [{ type: "string" }, { type: "null" }] },
                to_email: { anyOf: [{ type: "string" }, { type: "null" }] },
                message: { anyOf: [{ type: "string" }, { type: "null" }] },
                title: { anyOf: [{ type: "string" }, { type: "null" }] },
                price: { anyOf: [{ type: "string" }, { type: "null" }] },
                code: { anyOf: [{ type: "string" }, { type: "null" }] },
                source: { anyOf: [{ type: "string" }, { type: "null" }] },
                mode: { anyOf: [{ type: "string", enum: ["hold", "release"] }, { type: "null" }] },
                fulfillment_order_id: { anyOf: [{ type: "number" }, { type: "null" }] },
                reason_notes: { anyOf: [{ type: "string" }, { type: "null" }] },
                edit_summary: { anyOf: [{ type: "string" }, { type: "null" }] },
                requested_changes: { anyOf: [{ type: "string" }, { type: "null" }] },
                operations: {
                  anyOf: [
                    {
                      type: "array",
                      items: {
                        type: "object",
                        additionalProperties: false,
                        properties: {
                          type: {
                            type: "string",
                            enum: ["set_quantity", "remove_line_item", "add_variant"],
                          },
                          line_item_id: {
                            anyOf: [{ type: "string" }, { type: "number" }, { type: "null" }],
                          },
                          lineItemId: {
                            anyOf: [{ type: "string" }, { type: "number" }, { type: "null" }],
                          },
                          variant_id: {
                            anyOf: [{ type: "string" }, { type: "number" }, { type: "null" }],
                          },
                          variantId: {
                            anyOf: [{ type: "string" }, { type: "number" }, { type: "null" }],
                          },
                          quantity: { anyOf: [{ type: "number" }, { type: "null" }] },
                        },
                        required: [
                          "type",
                          "line_item_id",
                          "lineItemId",
                          "variant_id",
                          "variantId",
                          "quantity",
                        ],
                      },
                    },
                    { type: "null" },
                  ],
                },
                line_item_id: {
                  anyOf: [{ type: "string" }, { type: "number" }, { type: "null" }],
                },
                lineItemId: {
                  anyOf: [{ type: "string" }, { type: "number" }, { type: "null" }],
                },
                variant_id: {
                  anyOf: [{ type: "string" }, { type: "number" }, { type: "null" }],
                },
                variantId: {
                  anyOf: [{ type: "string" }, { type: "number" }, { type: "null" }],
                },
                quantity: { anyOf: [{ type: "number" }, { type: "null" }] },
              },
              required: [
                "shipping_address",
                "note",
                "tag",
                "amount",
                "currency",
                "reason",
                "refund",
                "restock",
                "email",
                "phone",
                "to_email",
                "message",
                "title",
                "price",
                "code",
                "source",
                "mode",
                "fulfillment_order_id",
                "reason_notes",
                "edit_summary",
                "requested_changes",
                "operations",
                "line_item_id",
                "lineItemId",
                "variant_id",
                "variantId",
                "quantity",
              ],
            },
          },
          required: ["type", "orderId", "payload"],
        },
      },
    },
    required: ["reply", "actions"],
  },
};
