const AUTOMATION_ACTION_PAYLOAD_SCHEMA = {
  type: "object",
  additionalProperties: false,
  properties: {
    shipping_address: {
      anyOf: [
        {
          type: "object",
          additionalProperties: false,
          properties: {
            name: { anyOf: [{ type: "string" }, { type: "null" }] },
            address1: { anyOf: [{ type: "string" }, { type: "null" }] },
            address2: { anyOf: [{ type: "string" }, { type: "null" }] },
            zip: { anyOf: [{ type: "string" }, { type: "null" }] },
            city: { anyOf: [{ type: "string" }, { type: "null" }] },
            country: { anyOf: [{ type: "string" }, { type: "null" }] },
            phone: { anyOf: [{ type: "string" }, { type: "null" }] },
          },
          required: ["name", "address1", "address2", "zip", "city", "country", "phone"],
        },
        { type: "null" },
      ],
    },
    note: { anyOf: [{ type: "string" }, { type: "null" }] },
    tag: { anyOf: [{ type: "string" }, { type: "null" }] },
    amount: { anyOf: [{ type: "number" }, { type: "null" }] },
    currency: { anyOf: [{ type: "string" }, { type: "null" }] },
    reason: { anyOf: [{ type: "string" }, { type: "null" }] },
    return_reason: { anyOf: [{ type: "string" }, { type: "null" }] },
    refund: { anyOf: [{ type: "boolean" }, { type: "null" }] },
    restock: { anyOf: [{ type: "boolean" }, { type: "null" }] },
    email: { anyOf: [{ type: "string" }, { type: "null" }] },
    phone: { anyOf: [{ type: "string" }, { type: "null" }] },
    to_email: { anyOf: [{ type: "string" }, { type: "null" }] },
    message: { anyOf: [{ type: "string" }, { type: "null" }] },
    title: { anyOf: [{ type: "string" }, { type: "null" }] },
    price: { anyOf: [{ type: "string" }, { type: "null" }] },
    code: { anyOf: [{ type: "string" }, { type: "null" }] },
    source: { anyOf: [{ type: "string" }, { type: "null" }] },
    mode: { anyOf: [{ type: "string", enum: ["hold", "release"] }, { type: "null" }] },
    fulfillment_order_id: { anyOf: [{ type: "number" }, { type: "null" }] },
    reason_notes: { anyOf: [{ type: "string" }, { type: "null" }] },
    return_line_item_id: { anyOf: [{ type: "string" }, { type: "number" }, { type: "null" }] },
    returnLineItemId: { anyOf: [{ type: "string" }, { type: "number" }, { type: "null" }] },
    return_quantity: { anyOf: [{ type: "number" }, { type: "null" }] },
    exchange_variant_id: { anyOf: [{ type: "string" }, { type: "number" }, { type: "null" }] },
    exchangeVariantId: { anyOf: [{ type: "string" }, { type: "number" }, { type: "null" }] },
    exchange_quantity: { anyOf: [{ type: "number" }, { type: "null" }] },
    edit_summary: { anyOf: [{ type: "string" }, { type: "null" }] },
    requested_changes: { anyOf: [{ type: "string" }, { type: "null" }] },
    operations: {
      anyOf: [
        {
          type: "array",
          items: {
            type: "object",
            additionalProperties: false,
            properties: {
              type: {
                type: "string",
                enum: ["set_quantity", "remove_line_item", "add_variant"],
              },
              line_item_id: { anyOf: [{ type: "string" }, { type: "number" }, { type: "null" }] },
              lineItemId: { anyOf: [{ type: "string" }, { type: "number" }, { type: "null" }] },
              variant_id: { anyOf: [{ type: "string" }, { type: "number" }, { type: "null" }] },
              variantId: { anyOf: [{ type: "string" }, { type: "number" }, { type: "null" }] },
              quantity: { anyOf: [{ type: "number" }, { type: "null" }] },
            },
            required: ["type", "line_item_id", "lineItemId", "variant_id", "variantId", "quantity"],
          },
        },
        { type: "null" },
      ],
    },
    line_item_id: { anyOf: [{ type: "string" }, { type: "number" }, { type: "null" }] },
    lineItemId: { anyOf: [{ type: "string" }, { type: "number" }, { type: "null" }] },
    variant_id: { anyOf: [{ type: "string" }, { type: "number" }, { type: "null" }] },
    variantId: { anyOf: [{ type: "string" }, { type: "number" }, { type: "null" }] },
    quantity: { anyOf: [{ type: "number" }, { type: "null" }] },
  },
  required: [
    "shipping_address",
    "note",
    "tag",
    "amount",
    "currency",
    "reason",
    "return_reason",
    "refund",
    "restock",
    "email",
    "phone",
    "to_email",
    "message",
    "title",
    "price",
    "code",
    "source",
    "mode",
    "fulfillment_order_id",
    "reason_notes",
    "return_line_item_id",
    "returnLineItemId",
    "return_quantity",
    "exchange_variant_id",
    "exchangeVariantId",
    "exchange_quantity",
    "edit_summary",
    "requested_changes",
    "operations",
    "line_item_id",
    "lineItemId",
    "variant_id",
    "variantId",
    "quantity",
  ],
};

const AUTOMATION_ACTION_SCHEMA = {
  type: "object",
  additionalProperties: false,
  properties: {
    type: {
      type: "string",
      enum: [
        "update_shipping_address",
        "cancel_order",
        "refund_order",
        "create_exchange_request",
        "change_shipping_method",
        "hold_or_release_fulfillment",
        "edit_line_items",
        "update_customer_contact",
        "add_note",
        "add_tag",
        "add_internal_note_or_tag",
        "resend_confirmation_or_invoice",
        "lookup_order_status",
        "fetch_tracking",
      ],
    },
    orderId: { type: "number" },
    payload: AUTOMATION_ACTION_PAYLOAD_SCHEMA,
  },
  required: ["type", "orderId", "payload"],
};

export const PERSONA_REPLY_JSON_SCHEMA = {
  name: "persona_reply",
  strict: true,
  schema: {
    type: "object",
    additionalProperties: false,
    properties: {
      reply: { type: "string" },
      actions: {
        type: "array",
        items: AUTOMATION_ACTION_SCHEMA,
      },
    },
    required: ["reply", "actions"],
  },
};

export const ACTION_DECISION_JSON_SCHEMA = {
  name: "action_decision",
  strict: true,
  schema: {
    type: "object",
    additionalProperties: false,
    properties: {
      summary: { type: "string" },
      actions: {
        type: "array",
        items: AUTOMATION_ACTION_SCHEMA,
      },
    },
    required: ["summary", "actions"],
  },
};

export const REPLY_ONLY_JSON_SCHEMA = {
  name: "reply_only",
  strict: true,
  schema: {
    type: "object",
    additionalProperties: false,
    properties: {
      reply: { type: "string" },
      quality_check: {
        type: "object",
        additionalProperties: false,
        properties: {
          answers_core_question: { type: "boolean" },
          matches_brand_voice: { type: "boolean" },
          contains_ungrounded_claims: { type: "boolean" },
          ready_to_send: { type: "boolean" },
        },
        required: [
          "answers_core_question",
          "matches_brand_voice",
          "contains_ungrounded_claims",
          "ready_to_send",
        ],
      },
    },
    required: ["reply", "quality_check"],
  },
};
