import { assertEquals } from "jsr:@std/assert@1";
import { fetchTrackingDetailForCandidate } from "../../../tracking.ts";
const nativeFallback = { carrier: "PostNord", trackingNumber: "000TEST123", trackingUrl: "https://carrier.example.test/track", statusText: "Shipped - follow the parcel via tracking link.", lookupSource: "shopify_fallback", lookupDetail: "api_failed:http_403", snapshot: { statusCode: "in_transit", events: [] } };
const verified = { carrier: "PostNord", trackingNumber: "000TEST123", statusText: "Delivered", lookupSource: "ship24_api", lookupDetail: "ok", snapshot: { statusCode: "delivered", events: [] } };
for (const issue of ["api_failed:http_403", "api_failed:api_key_missing", "public_page_no_match"]) Deno.test(`native ${issue} uses verified configured fallback`, async () => {
 let calls=0; const detail=await fetchTrackingDetailForCandidate({company:"PostNord",trackingNumber:"000TEST123",trackingUrl:"https://carrier.example.test/track"},{fetchPostNord:async()=>({...nativeFallback,lookupDetail:issue}),ship24Configured:()=>true,fetchShip24:async(number,options)=>{calls++;assertEquals(number,"000TEST123");assertEquals(options?.trackingUrl,"https://carrier.example.test/track");return verified;}});
 assertEquals(calls,1);assertEquals(detail,verified);
});
Deno.test("verified native carrier data does not call fallback",async()=>{let calls=0;const native={...verified,lookupSource:"postnord_api"};const result=await fetchTrackingDetailForCandidate({company:"PostNord",trackingNumber:"000TEST123"},{fetchPostNord:async()=>native,ship24Configured:()=>true,fetchShip24:async()=>{calls++;return verified;}});assertEquals(result,native);assertEquals(calls,0);});
Deno.test("missing fallback configuration retains bounded native no-data",async()=>{let calls=0;const result=await fetchTrackingDetailForCandidate({company:"PostNord",trackingNumber:"000TEST123"},{fetchPostNord:async()=>nativeFallback,ship24Configured:()=>false,fetchShip24:async()=>{calls++;return verified;}});assertEquals(result,nativeFallback);assertEquals(calls,0);});
for(const detail of [{...verified,lookupDetail:"pending"},{...verified,lookupSource:"shopify_fallback",lookupDetail:"api_failed:http_500"}])Deno.test(`unverified fallback ${detail.lookupDetail} never creates carrier facts`,async()=>{const result=await fetchTrackingDetailForCandidate({company:"PostNord",trackingNumber:"000TEST123"},{fetchPostNord:async()=>nativeFallback,ship24Configured:()=>true,fetchShip24:async()=>detail});assertEquals(result,nativeFallback);});
