import {describe,it,expect,vi,afterEach} from 'vitest';
import {ShopifyOperationalProvider} from '../shopify-operational';
import {resolveOperationalPermissions,createOperationalRuntime} from '../../server/greenfield-operational';
const tenant={workspaceId:'workspace',shopId:'shop',customerEmail:'customer@example.test'};
const command={action:'cancel_order',orderId:'101',orderReference:'101',customerEmail:tenant.customerEmail,reason:'Customer request'};
const options={workspaceId:'workspace',shopId:'shop',shopDomain:'fixture.myshopify.com',accessToken:'fake-token'};
function setup(payload={data:{orderCancel:{job:{id:'job-1',done:false},orderCancelUserErrors:[]}}},enabled=true){const fetchImpl=vi.fn(async()=>({ok:true,json:async()=>payload}));return {fetchImpl,provider:new ShopifyOperationalProvider({...options,mutationsEnabled:enabled,fetchImpl})};}
afterEach(()=>vi.unstubAllEnvs());
describe('Shopify mutation transport contract — fake HTTP only',()=>{
 it('disabled transport sends no request',async()=>{const s=setup(undefined,false);expect(await s.provider.mutate(command)).toMatchObject({accepted:false});expect(s.fetchImpl).not.toHaveBeenCalled();});
 it('unsupported line mutation sends no request',async()=>{const s=setup();expect(s.provider.supports('update_order_line')).toBe(false);expect(await s.provider.mutate({...command,action:'update_order_line'})).toMatchObject({accepted:false});expect(s.fetchImpl).not.toHaveBeenCalled();});
 it('binds cancellation to exact order and treats async job as acceptance only',async()=>{const s=setup();expect(await s.provider.mutate(command)).toEqual({accepted:true});const [url,request]=s.fetchImpl.mock.calls[0];expect(url).toBe('https://fixture.myshopify.com/admin/api/2026-07/graphql.json');expect(JSON.parse(request.body).variables).toEqual({orderId:'gid://shopify/Order/101'});expect(JSON.parse(request.body).query).not.toMatch(/refundMethod|refundAmount/);expect(request.redirect).toBe('error');});
 for(const payload of [{errors:[{message:'failure'}]},{data:{orderCancel:{orderCancelUserErrors:[{message:'blocked'}]}}},{data:{orderCancel:{job:null,orderCancelUserErrors:[]}}}])it('rejects GraphQL error, user error or missing job '+JSON.stringify(payload),async()=>{expect(await setup(payload).provider.mutate(command)).toMatchObject({accepted:false});});
 it('rejects foreign object ID before transport',async()=>{const s=setup();expect(await s.provider.mutate({...command,orderId:'gid://shopify/Customer/101'})).toMatchObject({accepted:false});expect(s.fetchImpl).not.toHaveBeenCalled();});
 it('requires structured address before transport',async()=>{const s=setup();expect(await s.provider.mutate({...command,action:'update_address'})).toMatchObject({accepted:false});expect(s.fetchImpl).not.toHaveBeenCalled();});
 it('serializes exact structured address and verifies returned order identity',async()=>{const s=setup({data:{orderUpdate:{order:{id:'gid://shopify/Order/101'},userErrors:[]}}});const address={address1:'12 Street',city:'City',zip:'1000',countryCode:'DK'};expect(await s.provider.mutate({...command,action:'update_address',address})).toEqual({accepted:true});expect(JSON.parse(s.fetchImpl.mock.calls[0][1].body).variables).toEqual({input:{id:'gid://shopify/Order/101',shippingAddress:address}});});
 it('rejects wrong returned order',async()=>{const s=setup({data:{orderUpdate:{order:{id:'gid://shopify/Order/202'},userErrors:[]}}});expect(await s.provider.mutate({...command,action:'update_address',address:{address1:'a',city:'b',zip:'c',countryCode:'DK'}})).toMatchObject({accepted:false,error:'provider_response_not_bound'});});
 it('rejects HTTP error',async()=>{const s=setup();s.fetchImpl.mockResolvedValue({ok:false});expect(await s.provider.mutate(command)).toMatchObject({accepted:false,error:'provider_http_error'});});
 it('rejects non-Shopify domain',()=>expect(()=>new ShopifyOperationalProvider({...options,shopDomain:'foreign.test'})).toThrow());
});
describe('Server merchant permissions',()=>{
 it('defaults every family to disabled',()=>{const config=resolveOperationalPermissions(tenant,'{}');expect(Object.values(config.actions).every(a=>a.mode==='disabled')).toBe(true);});
 it('invalid configuration fails closed',()=>{expect(resolveOperationalPermissions(tenant,'bad').actions.cancel_order.mode).toBe('disabled');});
 it('scopes family modes and explicit confirmation to workspace and shop',()=>{const raw=JSON.stringify({workspace:{shop:{cancel_order:{mode:'auto'},update_address:{mode:'hitl',requireConfirmation:true},update_order_line:{mode:'unknown'}}}});expect(resolveOperationalPermissions(tenant,raw).actions).toEqual({cancel_order:{mode:'auto',requireConfirmation:false},update_address:{mode:'hitl',requireConfirmation:true},update_order_line:{mode:'disabled',requireConfirmation:false}});expect(resolveOperationalPermissions({...tenant,workspaceId:'foreign'},raw).actions.cancel_order.mode).toBe('disabled');expect(resolveOperationalPermissions({...tenant,shopId:'foreign'},raw).actions.cancel_order.mode).toBe('disabled');});
 it('Playground always disables real provider mutation even with server kill switch enabled',()=>{vi.stubEnv('GREENFIELD_ALLOW_PROVIDER_MUTATIONS','true');const runtime=createOperationalRuntime(tenant,{shop_domain:options.shopDomain,access_token:'fake'}, {},'playground');expect(runtime.mutationProvider.mutationsEnabled).toBe(false);});
 it('Inbox requires explicit server kill switch',()=>{vi.stubEnv('GREENFIELD_ALLOW_PROVIDER_MUTATIONS','false');expect(createOperationalRuntime(tenant,{shop_domain:options.shopDomain,access_token:'fake'}, {},'support_inbox').mutationProvider.mutationsEnabled).toBe(false);});
 it('invalid adapter configuration preserves read-only runtime',()=>{const catalog={};const runtime=createOperationalRuntime(tenant,{shop_domain:'invalid',access_token:'fake'},catalog,'support_inbox');expect(runtime.catalog).toBe(catalog);expect(runtime.mutationProvider).toBeUndefined();});
});

import {ShopifyReadOnlyProvider} from '../shopify-read-only';
describe('Live order-line catalog reads',()=>{
 function catalog(locations=[{id:1,active:true}],productId=1){const fetchImpl=vi.fn(async(url,init)=>{expect(init.method).toBe('GET');let body=String(url).includes('products/')?{product:{id:productId,variants:[{id:11,title:'Blue / L',option1:'Blue',option2:'L',price:'100.00',inventory_management:'shopify',inventory_policy:'deny',inventory_quantity:5}]}}:String(url).includes('locations.json')?{locations}:{shop:{currency:'DKK'}};return {ok:true,json:async()=>body};});return {fetchImpl,provider:new ShopifyReadOnlyProvider({shopDomain:'fixture.myshopify.com',accessToken:'fake',fetchImpl})};}
 it('retrieves exact canonical variants, stock and shop currency through GET only',async()=>{const s=catalog();expect(await s.provider.getOrderLineVariants('1')).toEqual([{id:'11',productId:'1',title:'Blue / L',options:['Blue','L'],price:'100.00',currency:'DKK',availableQuantity:5,availability:'available'}]);expect(s.fetchImpl).toHaveBeenCalledTimes(3);});
 it('does not invent sellable quantity across multiple locations',async()=>{const s=catalog([{id:1},{id:2}]);expect((await s.provider.getOrderLineVariants('1'))[0]).toMatchObject({availableQuantity:null,availability:'unknown'});});
 it('rejects mismatched product identity',async()=>expect(await catalog(undefined,2).provider.getOrderLineVariants('1')).toEqual([]));
 it('rejects an invalid catalog identifier without transport',async()=>{const s=catalog();expect(await s.provider.getOrderLineVariants('foreign')).toEqual([]);expect(s.fetchImpl).not.toHaveBeenCalled();});
});
