import {describe,it,expect,vi} from 'vitest';
import {resolveOperationalAction,isVerifiedOperationalOutcome,operationalReply,linePriceImpact,moneyMinor} from '../operational-execution';
import {prepareCaseContext,advanceCaseContext} from '../case-state';
import {InMemoryCommerceProvider} from '../providers';
const tenant={workspaceId:'workspace',shopId:'shop',caseId:'case',customerEmail:'customer@example.test'};
const address={address1:'12 Street',city:'City',zip:'1000',countryCode:'DK'};
const baseOrder=()=>({id:'order-101',orderNumber:'101',status:'paid',fulfillmentStatus:null,currency:'DKK',customerEmail:tenant.customerEmail,items:[{id:'line-1',title:'Hoodie',variantTitle:'Black / M',productId:'product-1',variantId:'variant-1',quantity:2,unitPrice:'100.00',totalDiscount:'0.00'}],fulfillments:[]});
const variants=()=>[{id:'variant-1',productId:'product-1',title:'Black / M',options:['Black','M'],price:'100.00',currency:'DKK',availableQuantity:20,availability:'available'},{id:'variant-2',productId:'product-1',title:'Blue / L',options:['Blue','L'],price:'100.00',currency:'DKK',availableQuantity:20,availability:'available'}];
function setup({action='cancel_order',channel='playground',permission='auto',order=baseOrder(),complete=true,variantList=variants(),sourceItem='Hoodie Black M',targetVariant='Blue L',quantity=null,requireConfirmation=false}={}){
 const ir={actions:[{action,sourceText:'Explicit customer request',orderReference:'101',addressProvided:complete}],...(action==='update_order_line'?{lineChange:{sourceItem,targetVariant,quantity}}:{}),...(action==='update_address'&&complete?{address:{value:'12 Street, City 1000, Denmark',complete:true,details:address}}:{})};
 const context=advanceCaseContext({...prepareCaseContext(undefined,tenant),activeOrder:{requestedOrderId:'101',state:'verified',order}},ir,'Explicit customer request');
 const commerce=new InMemoryCommerceProvider({customer:{email:tenant.customerEmail},orders:[order]});
 const mutate=vi.fn(async command=>{if(command.action==='cancel_order')order.status='cancelled';if(command.action==='update_address')order.shippingAddress={...command.address};if(command.action==='update_order_line')order.items=order.items.map(i=>i.id===command.lineId?{...i,variantId:command.variantId,quantity:command.quantity}:i);return {accepted:true};});
 const runtime={permissions:{workspaceId:tenant.workspaceId,shopId:tenant.shopId,actions:{[action]:{mode:permission,requireConfirmation}}},catalog:{getOrderLineVariants:vi.fn(async()=>variantList)},mutationProvider:{scope:{workspaceId:tenant.workspaceId,shopId:tenant.shopId},supports:()=>true,mutationsEnabled:true,mutate}};
 const request={tenant,commerce,runtime,channel};return {ir,context,commerce,runtime,request,mutate,order,async run(){const result=await resolveOperationalAction(request,context,ir);if(result)expect(isVerifiedOperationalOutcome(result)).toBe(true);return result;}};
}
describe('Cancellation execution',()=>{
 for(const channel of ['playground','support_inbox'])it(`executes eligible cancellation semantics in ${channel} without confirmation`,async()=>{const s=setup({channel});const r=await s.run();expect(r.status).toBe(channel==='playground'?'SIMULATED':'EXECUTED');expect(r.after.status).toBe('cancelled');expect(r.readBackVerified).toBe(true);expect(r.question).toBeNull();expect(s.mutate).toHaveBeenCalledTimes(channel==='playground'?0:1);expect(operationalReply(r)).not.toMatch(/until you confirm|are you sure/i);});
 for(const state of ['fulfilled','shipped','delivered','partial'])it(`blocks cancellation on ${state}`,async()=>{const o=baseOrder();o.fulfillmentStatus=state;const s=setup({order:o});const r=await s.run();expect(r.status).toBe('BLOCKED');expect(s.mutate).not.toHaveBeenCalled();});
 it('retains HITL with no execution claim',async()=>{const s=setup({permission:'hitl'});const r=await s.run();expect(r.status).toBe('PROPOSED');expect(r.executed).toBe(false);expect(s.mutate).not.toHaveBeenCalled();expect(operationalReply(r)).not.toContain('has been cancelled');});
 it('honors explicit merchant confirmation policy',async()=>{const s=setup({requireConfirmation:true});const r=await s.run();expect(r.question).toMatch(/confirm/i);expect(s.mutate).not.toHaveBeenCalled();});
});
describe('Address execution',()=>{
 for(const channel of ['playground','support_inbox'])it(`updates complete address in ${channel} without confirmation`,async()=>{const s=setup({action:'update_address',channel});const r=await s.run();expect(r.after.shippingAddress).toEqual({...address,address2:''});expect(r.readBackVerified).toBe(true);expect(r.question).toBeNull();expect(s.mutate).toHaveBeenCalledTimes(channel==='playground'?0:1);});
 it('asks only for a genuinely missing address',async()=>{const s=setup({action:'update_address',complete:false});const r=await s.run();expect(r.question).toBe('What is the complete new delivery address?');expect(s.mutate).not.toHaveBeenCalled();});
 for(const state of ['fulfilled','shipped','delivered'])it(`blocks address after ${state}`,async()=>{const o=baseOrder();o.fulfillmentStatus=state;const s=setup({action:'update_address',order:o});expect((await s.run()).status).toBe('BLOCKED');});
 it('supports HITL for address',async()=>{const s=setup({action:'update_address',permission:'hitl'});expect((await s.run()).status).toBe('PROPOSED');expect(s.mutate).not.toHaveBeenCalled();});
});
describe('Order-line resolution and price impact',()=>{
 for(const target of ['Blue L','Blue','L'])it(`resolves live color/size variant ${target}`,async()=>{const s=setup({action:'update_order_line',targetVariant:target});const r=await s.run();expect(r.command.variantId).toBe('variant-2');expect(r.status).toBe('SIMULATED');expect(r.after.items[0].variantId).toBe('variant-2');expect(s.mutate).not.toHaveBeenCalled();});
 it('executes same-price line contract in inbox auto',async()=>{const s=setup({action:'update_order_line',channel:'support_inbox'});const r=await s.run();expect(r.status).toBe('EXECUTED');expect(s.mutate).toHaveBeenCalledOnce();});
 it('resolves quantity reduction but hands refund handling to a human',async()=>{const s=setup({action:'update_order_line',targetVariant:null,quantity:1});const r=await s.run();expect(r.command.quantity).toBe(1);expect(r.priceImpact).toMatchObject({oldLineValue:'200.00',newLineValue:'100.00',delta:'-100.00',refundHandlingRequired:true});expect(r.status).toBe('PROPOSED');expect(s.mutate).not.toHaveBeenCalled();});
 it('blocks unavailable inventory',async()=>{const list=variants();list[1].availableQuantity=0;list[1].availability='unavailable';const s=setup({action:'update_order_line',variantList:list});expect((await s.run()).reason).toBe('target_inventory_unavailable');});
 it('asks for an ambiguous source line',async()=>{const o=baseOrder();o.items.push({...o.items[0],id:'line-2'});const s=setup({action:'update_order_line',order:o});expect((await s.run()).reason).toBe('source_line_ambiguous');});
 it('asks for an ambiguous target variant',async()=>{const list=variants();list.push({...list[1],id:'variant-3',title:'Blue / M',options:['Blue','M']});const s=setup({action:'update_order_line',targetVariant:'Blue',variantList:list});expect((await s.run()).reason).toBe('target_variant_ambiguous');});
 it('does not invent an unknown variant',async()=>{const s=setup({action:'update_order_line',targetVariant:'Green XL'});expect((await s.run()).reason).toBe('target_variant_unknown');});
 it('blocks fulfilled source line',async()=>{const o=baseOrder();o.fulfillmentStatus='fulfilled';const s=setup({action:'update_order_line',order:o});expect((await s.run()).reason).toBe('affected_line_fulfilled_or_state_unknown');});
 for(const affected of [true,false])it(`scopes partial fulfillment; affected line dispatched ${affected}`,async()=>{const o=baseOrder();o.fulfillmentStatus='partial';o.items.push({id:'other-line',title:'Other item',quantity:1,variantId:'other-variant'});o.fulfillments=[{id:'shipment',status:'success',itemMappingStatus:'verified',items:[{orderLineItemId:affected?'line-1':'other-line',quantity:1}]}];const s=setup({action:'update_order_line',order:o});expect((await s.run()).status).toBe(affected?'BLOCKED':'SIMULATED');});
 for(const price of ['110.00','90.00'])it(`models ${price} price change and prevents silent charge/refund`,async()=>{const list=variants();list[1].price=price;const s=setup({action:'update_order_line',variantList:list,channel:'support_inbox'});const r=await s.run();expect(r.status).toBe('PROPOSED');expect(r.priceImpact.oldLineValue).toBe('200.00');expect(r.priceImpact.newLineValue).toBe(price==='110.00'?'220.00':'180.00');expect(s.mutate).not.toHaveBeenCalled();});
 it('hands a complete line context to a human when provider lacks mutation support',async()=>{const s=setup({action:'update_order_line'});s.runtime.mutationProvider.supports=()=>false;const r=await s.run();expect(r.reason).toBe('provider_capability_unavailable');expect(r.lineContext).toMatchObject({line:{id:'line-1',variantId:'variant-1'},target:{id:'variant-2',availableQuantity:20},requestedQuantity:2});expect(r.priceImpact.delta).toBe('0.00');expect(s.mutate).not.toHaveBeenCalled();});
 it('does not infer cross-currency price equivalence',async()=>{const list=variants();list[1].currency='EUR';const s=setup({action:'update_order_line',variantList:list});expect((await s.run()).reason).toBe('price_impact_unknown');});
});
describe('Authorization and read-back negatives',()=>{
 it('blocks absent merchant permission',async()=>{const s=setup({permission:'disabled'});expect((await s.run()).reason).toBe('merchant_permission_disabled');expect(s.mutate).not.toHaveBeenCalled();});
 for(const patch of [{workspaceId:'other'},{shopId:'other'},{caseId:'other'},{customerEmail:'other@example.test'}])it(`rejects stale or foreign CaseState ${JSON.stringify(patch)}`,async()=>{const s=setup();s.context.caseState.scope={...s.context.caseState.scope,...patch};expect((await s.run()).status).toBe('BLOCKED');expect(s.mutate).not.toHaveBeenCalled();});
 it('rejects provider customer mismatch',async()=>{const s=setup();vi.spyOn(s.commerce,'getCustomer').mockResolvedValue({email:'other@example.test'});expect((await s.run()).reason).toBe('customer_identity_mismatch');expect(s.mutate).not.toHaveBeenCalled();});
 it('rejects the wrong returned order',async()=>{const s=setup();vi.spyOn(s.commerce,'getOrder').mockResolvedValue({...baseOrder(),id:'other',orderNumber:'202'});expect((await s.run()).reason).toBe('order_scope_mismatch');expect(s.mutate).not.toHaveBeenCalled();});
 it('blocks missing TurnIR despite pending intent',async()=>{const s=setup();expect(await resolveOperationalAction(s.request,s.context,null)).toBeNull();expect(s.mutate).not.toHaveBeenCalled();});
 it('blocks foreign mutation provider scope',async()=>{const s=setup({channel:'support_inbox'});s.runtime.mutationProvider.scope.workspaceId='other';expect((await s.run()).reason).toBe('mutation_provider_scope_unavailable');expect(s.mutate).not.toHaveBeenCalled();});
 it('does not call a provider with mutations disabled',async()=>{const s=setup({channel:'support_inbox'});s.runtime.mutationProvider.mutationsEnabled=false;expect((await s.run()).reason).toBe('provider_mutations_disabled');expect(s.mutate).not.toHaveBeenCalled();});
 it('never equates accepted mutation with verified success',async()=>{const s=setup({channel:'support_inbox'});s.mutate.mockResolvedValue({accepted:true});const r=await s.run();expect(r.reason).toBe('read_back_did_not_verify_change');expect(r.executed).toBe(false);expect(operationalReply(r)).not.toContain('has been cancelled');});
 it('does not claim completion after provider rejection',async()=>{const s=setup({channel:'support_inbox'});s.mutate.mockResolvedValue({accepted:false,error:'provider_rejected'});const r=await s.run();expect(r.status).toBe('PROPOSED');expect(r.executed).toBe(false);});
 it('does not retry an ambiguous mutation failure',async()=>{const s=setup({channel:'support_inbox'});s.mutate.mockRejectedValue(new Error('Timeout'));expect((await s.run()).executed).toBe(false);expect(s.mutate).toHaveBeenCalledOnce();});
 it('rejects a wrong-order read-back',async()=>{const s=setup({channel:'support_inbox'});vi.spyOn(s.commerce,'getOrder').mockResolvedValueOnce(s.order).mockResolvedValueOnce(s.order).mockResolvedValueOnce({...s.order,id:'foreign',orderNumber:'202'});expect((await s.run()).reason).toBe('read_back_scope_mismatch');});
 it('does not authorize a changed fulfilled state from cached CaseState',async()=>{const s=setup();vi.spyOn(s.commerce,'getOrder').mockResolvedValue({...s.order,fulfillmentStatus:'fulfilled'});expect((await s.run()).status).toBe('BLOCKED');expect(s.mutate).not.toHaveBeenCalled();});
});
describe('Decimal money',()=>{
 it('preserves exact minor-unit values',()=>{expect(moneyMinor('0.29','DKK')).toBe(29);expect(moneyMinor('100','JPY')).toBe(100);expect(moneyMinor('1.123','KWD')).toBe(1123);expect(moneyMinor('0.001','DKK')).toBeNull();});
 it('includes source discount in price delta',()=>{const o=baseOrder();o.items[0].totalDiscount='20.00';expect(linePriceImpact(o,o.items[0],variants()[1],2).delta).toBe('20.00');});
});

describe('Fresh transition verification',()=>{
 it('does not mutate when fulfillment changes during preparation',async()=>{const s=setup({channel:'support_inbox'});vi.spyOn(s.commerce,'getOrder').mockResolvedValueOnce(s.order).mockResolvedValueOnce({...s.order,fulfillmentStatus:'fulfilled'});expect((await s.run()).reason).toBe('order_changed_before_execution');expect(s.mutate).not.toHaveBeenCalled();});
 it('does not claim item success with an unexpected price change in read-back',async()=>{const s=setup({action:'update_order_line',channel:'support_inbox'});s.mutate.mockImplementation(async c=>{s.order.items[0].variantId=c.variantId;s.order.items[0].unitPrice='110.00';return {accepted:true};});const r=await s.run();expect(r.executed).toBe(false);expect(r.reason).toBe('read_back_did_not_verify_change');});
 it('clears an old apartment when the complete new address has none',async()=>{const o=baseOrder();o.shippingAddress={address1:'Old Street',address2:'Apartment 9',city:'City',zip:'1000',countryCode:'DK'};const s=setup({action:'update_address',channel:'support_inbox',order:o});const r=await s.run();expect(r.command.address.address2).toBe('');expect(r.after.shippingAddress.address2).toBe('');expect(r.executed).toBe(true);});
});

describe('Unknown line fulfillment',()=>{
 it('blocks unknown fulfillment state',async()=>{const o=baseOrder();o.fulfillmentStatus='unknown';const s=setup({action:'update_order_line',order:o});expect((await s.run()).reason).toBe('affected_line_fulfilled_or_state_unknown');expect(s.mutate).not.toHaveBeenCalled();});
 it('blocks malformed partial fulfillment quantities',async()=>{const o=baseOrder();o.fulfillmentStatus='partial';o.fulfillments=[{id:'shipment',status:'success',itemMappingStatus:'verified',items:[{orderLineItemId:'line-1'}]}];const s=setup({action:'update_order_line',order:o});expect((await s.run()).reason).toBe('affected_line_fulfilled_or_state_unknown');expect(s.mutate).not.toHaveBeenCalled();});
});
