-- Stage 4B-3-2: structured, platform-neutral product specs.
--
-- Lets Sona compare products from curated, confirmed specs instead of
-- manual_text / prose retrieval. product_id NULL = brand-wide spec; a
-- product-specific row overrides the brand-wide one at runtime. Tenancy uses
-- shop_ref_id (-> shops.id), never the legacy shop_products.shop_id. Additive.

create table if not exists public.shop_product_specs (
  id bigint generated by default as identity primary key,
  shop_ref_id uuid not null references public.shops(id) on delete cascade,
  workspace_id uuid not null,
  product_id bigint null references public.shop_products(id) on delete cascade,
  spec_key text not null,
  spec_group text not null,
  spec_value text not null,
  value_bool boolean null,
  value_num numeric null,
  unit text null,
  display_order int not null default 0,
  comparable boolean not null default true,
  source text not null default 'manual',
  confidence text not null default 'confirmed'
    check (confidence in ('confirmed', 'suggested')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint shop_product_specs_spec_key_check
    check (length(btrim(spec_key)) > 0),
  constraint shop_product_specs_spec_group_check
    check (length(btrim(spec_group)) > 0)
);

-- One row per (shop, product-or-brand, spec_key). NULLS NOT DISTINCT (PG15+)
-- treats brand-wide rows (product_id null) as equal, enforcing a single
-- brand-wide value per spec_key without a coalesce-based index.
create unique index if not exists shop_product_specs_unique
  on public.shop_product_specs (shop_ref_id, product_id, spec_key)
  nulls not distinct;

create index if not exists shop_product_specs_scope_idx
  on public.shop_product_specs (shop_ref_id, workspace_id, product_id);

create index if not exists shop_product_specs_group_idx
  on public.shop_product_specs (shop_ref_id, spec_group, spec_key);

create or replace function public.set_shop_product_specs_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_shop_product_specs_updated_at
  on public.shop_product_specs;
create trigger trg_shop_product_specs_updated_at
before update on public.shop_product_specs
for each row
execute function public.set_shop_product_specs_updated_at();

alter table public.shop_product_specs enable row level security;

drop policy if exists shop_product_specs_select_scoped
  on public.shop_product_specs;
drop policy if exists shop_product_specs_modify_scoped
  on public.shop_product_specs;

-- Scoped to the shop's workspace members or owner — mirrors
-- shop_product_compatibility / knowledge_documents.
create policy shop_product_specs_select_scoped
on public.shop_product_specs
for select
to authenticated
using (
  exists (
    select 1
    from public.shops s
    where s.id = shop_product_specs.shop_ref_id
      and (
        (
          s.workspace_id is not null
          and exists (
            select 1
            from public.workspace_members wm
            where wm.workspace_id = s.workspace_id
              and wm.clerk_user_id = coalesce(auth.jwt() ->> 'sub', '')
          )
        )
        or s.owner_user_id::text = coalesce(auth.jwt() ->> 'supabase_user_id', '')
      )
  )
);

create policy shop_product_specs_modify_scoped
on public.shop_product_specs
for all
to authenticated
using (
  exists (
    select 1
    from public.shops s
    where s.id = shop_product_specs.shop_ref_id
      and (
        (
          s.workspace_id is not null
          and exists (
            select 1
            from public.workspace_members wm
            where wm.workspace_id = s.workspace_id
              and wm.clerk_user_id = coalesce(auth.jwt() ->> 'sub', '')
          )
        )
        or s.owner_user_id::text = coalesce(auth.jwt() ->> 'supabase_user_id', '')
      )
  )
)
with check (
  exists (
    select 1
    from public.shops s
    where s.id = shop_product_specs.shop_ref_id
      and (
        (
          s.workspace_id is not null
          and exists (
            select 1
            from public.workspace_members wm
            where wm.workspace_id = s.workspace_id
              and wm.clerk_user_id = coalesce(auth.jwt() ->> 'sub', '')
          )
        )
        or s.owner_user_id::text = coalesce(auth.jwt() ->> 'supabase_user_id', '')
      )
  )
);
