-- Stage 4B-3-1: structured, platform-neutral product compatibility.
--
-- Lets Sona answer "is this compatible with <platform>?" from curated, confirmed
-- rows instead of manual_text / prose retrieval. product_id NULL = brand-wide
-- fact; a product-specific row overrides the brand-wide one at runtime. Tenancy
-- uses shop_ref_id (-> shops.id), never the legacy shop_products.shop_id.
-- Additive; no data writes.

create table if not exists public.shop_product_compatibility (
  id bigint generated by default as identity primary key,
  shop_ref_id uuid not null references public.shops(id) on delete cascade,
  workspace_id uuid not null,
  product_id bigint null references public.shop_products(id) on delete cascade,
  target text not null,
  connection text not null,
  compatible text not null
    check (compatible in ('yes', 'no', 'partial')),
  reason text null,
  workaround text null,
  source text not null default 'manual',
  confidence text not null default 'confirmed'
    check (confidence in ('confirmed', 'suggested')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint shop_product_compatibility_target_check
    check (length(btrim(target)) > 0),
  constraint shop_product_compatibility_connection_check
    check (length(btrim(connection)) > 0)
);

-- One row per (shop, product-or-brand, target, connection). NULLS NOT DISTINCT
-- (Postgres 15+) treats brand-wide rows (product_id null) as equal, enforcing a
-- single brand-wide fact per target+connection without a coalesce-based index.
create unique index if not exists shop_product_compatibility_unique
  on public.shop_product_compatibility (shop_ref_id, product_id, target, connection)
  nulls not distinct;

-- Runtime lookup path.
create index if not exists shop_product_compatibility_lookup_idx
  on public.shop_product_compatibility (shop_ref_id, workspace_id, target, connection);

create index if not exists shop_product_compatibility_product_idx
  on public.shop_product_compatibility (product_id);

create or replace function public.set_shop_product_compatibility_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_shop_product_compatibility_updated_at
  on public.shop_product_compatibility;
create trigger trg_shop_product_compatibility_updated_at
before update on public.shop_product_compatibility
for each row
execute function public.set_shop_product_compatibility_updated_at();

alter table public.shop_product_compatibility enable row level security;

drop policy if exists shop_product_compatibility_select_scoped
  on public.shop_product_compatibility;
drop policy if exists shop_product_compatibility_modify_scoped
  on public.shop_product_compatibility;

-- Scoped to the shop's workspace members or owner — mirrors knowledge_documents.
create policy shop_product_compatibility_select_scoped
on public.shop_product_compatibility
for select
to authenticated
using (
  exists (
    select 1
    from public.shops s
    where s.id = shop_product_compatibility.shop_ref_id
      and (
        (
          s.workspace_id is not null
          and exists (
            select 1
            from public.workspace_members wm
            where wm.workspace_id = s.workspace_id
              and wm.clerk_user_id = coalesce(auth.jwt() ->> 'sub', '')
          )
        )
        or s.owner_user_id::text = coalesce(auth.jwt() ->> 'supabase_user_id', '')
      )
  )
);

create policy shop_product_compatibility_modify_scoped
on public.shop_product_compatibility
for all
to authenticated
using (
  exists (
    select 1
    from public.shops s
    where s.id = shop_product_compatibility.shop_ref_id
      and (
        (
          s.workspace_id is not null
          and exists (
            select 1
            from public.workspace_members wm
            where wm.workspace_id = s.workspace_id
              and wm.clerk_user_id = coalesce(auth.jwt() ->> 'sub', '')
          )
        )
        or s.owner_user_id::text = coalesce(auth.jwt() ->> 'supabase_user_id', '')
      )
  )
)
with check (
  exists (
    select 1
    from public.shops s
    where s.id = shop_product_compatibility.shop_ref_id
      and (
        (
          s.workspace_id is not null
          and exists (
            select 1
            from public.workspace_members wm
            where wm.workspace_id = s.workspace_id
              and wm.clerk_user_id = coalesce(auth.jwt() ->> 'sub', '')
          )
        )
        or s.owner_user_id::text = coalesce(auth.jwt() ->> 'supabase_user_id', '')
      )
  )
);
